### ISSUE TITLE
Not all results shown

### ISSUE THREAD

**Issue by michaelbaisch** [sigito/Linguee-Workflow-for-Alfred#44]
Hello,

I've noticed on a few occasions that sometimes results are omitted. Here an example where "salón" isn't shown `spanish <-> german`:

<img width="727" alt="Captura de Pantalla 2022-11-12 a las 17 04 23" src="https://user-images.githubusercontent.com/1899691/201483414-8fa116fe-3ad8-4c55-9788-a3a013c5d926.png">

**Comment by sigito** [comment]
Hi @michaelbaisch, thanks for the report. Unfortunately, this is as much as Linguee gives. You can see the same results would be shown when searching for "Wohnzimmer" on Linguee.com: 
<img width="916" alt="зображення" src="https://user-images.githubusercontent.com/1129082/202302652-ab308fcd-0c82-46ff-b3ee-13f6226062de.png">

An option would be to also fetch the result page, but it is going to be much slower, since it would need to be done for each result entry. I am not sure if I have time to do that, and if it would yield much benefit.

As a workaround, you could access the translation page by either pressing ⇧ (Shift) or ⌘ Y (Command+Y) to see a result page preview inside of Alfred, or by selecting the result and pressing ↩ (Return) to open the result page in a default browser.

**Comment by michaelbaisch** [comment]
Okay that's unfortunate. Probably something that is better fixed on Linguees side.
